return {
	SkinColor = {
		Color3.fromRGB(255, 204, 153),
		Color3.fromRGB(208, 162, 130),
		Color3.fromRGB(175, 121, 90),
		Color3.fromRGB(160, 95, 53),
		Color3.fromRGB(124, 92, 70),
	},
	
	face = {6375861873, 6443709454, 7802852009},
	
	Hair = {},
	
	PartsBody = {
		'HeadColor3','LeftArmColor3','LeftLegColor3','RightArmColor3','RightLegColor3','TorsoColor3'
	},
	
	WalkSpeed = {
		walk = 6,
		run = 10,
	},
	
	witheListStates = {"run","walk","idle","dead","deleted","action"}
}