return {
	Name = "Tutorial pls donate",
	Pasos = {
		
		{
			{
				["type"] = "Text",
				["Options"] = {
					Text = "hola a todos.",
					Size = Vector2.new(1,0),
					Font = Enum.Font.SourceSansLight,
				},
			},
		},
		
		{
			{
				["type"] = "Text",
				["Options"] = {
					Text = "esto es una prueba del tutorial.",
					Size = Vector2.new(1,0),
					Font = Enum.Font.SourceSansBold,
				},
			},
			{
				["type"] = "Image",
				["Options"] = {
					Image = "http://www.roblox.com/asset/?id=109251559",
				},
			},
		},
		{
			{
				["type"] = "Text",
				["Options"] = {
					Text = "Esto es una prueba para el copy and paste...",
					Size = Vector2.new(.3,0),
					Font = Enum.Font.SourceSansBold,
				},
			},
			{
				["type"] = "Copy",
				["Options"] = {
					Text = "https://www.roblox.com/games/132457887885313/The-Night-of-Panic",
				},
			},
		},
	}
}