return {
	Name = "Bienvenida",
	Pasos = {
		-- Página 1
		{
			{
				["type"] = "Text",
				["Options"] = {
					Text = "TE DAMOS LA BIENVENIDA A...",
					Size = Vector2.new(0.7,0),
					Font = Enum.Font.SourceSansBold,
				},
			},
			{
				["type"] = "Image",
				["Options"] = {
					Image = "http://www.roblox.com/asset/?id=95859443223104",
					Size = Vector2.new(3,3),
				},
			},
			{
				["type"] = "Text",
				["Options"] = {
					Text = "Vamos a introducirte y contarte todo lo que se puede hacer en este juego.",
					Size = Vector2.new(0.5,0),
					Font = Enum.Font.SourceSansLight,
				},
			},
		},
		-- Página 2
		{
			{
				["type"] = "Text",
				["Options"] = {
					Text = "Iconos",
					Size = Vector2.new(0.7,0),
					Font = Enum.Font.SourceSansBold,
				},
			},
			{
				["type"] = "Image",
				["Options"] = {
					Image = "http://www.roblox.com/asset/?id=98059459130936",
					Size = Vector2.new(2.5,0),
				},
			},
			{
				["type"] = "Text",
				["Options"] = {
					Text = "Con la tablet puedes administrar practicamente todo. Desde tu inventario hasta tus compras.",
					Size = Vector2.new(0.5,0),
					Font = Enum.Font.SourceSansLight,
				},
			},

		},
		-- Página 3
		{
			{
				["type"] = "Text",
				["Options"] = {
					Text = "Puedes tener tu propia casa!",
					Size = Vector2.new(0.7,0),
					Font = Enum.Font.SourceSansBold,
				},
			},
			{
				["type"] = "Image",
				["Options"] = {
					Image = "http://www.roblox.com/asset/?id=112782519673653",
					Size = Vector2.new(2.5,0),
				},
			},
			{
				["type"] = "Text",
				["Options"] = {
					Text = "Construye y da permisos a quien quieras.",
					Size = Vector2.new(0.5,0),
					Font = Enum.Font.SourceSansLight,
				},
			},

		},
		-- Página 4
		{
			{
				["type"] = "Text",
				["Options"] = {
					Text = "¡Tenemos un Karaoke!",
					Size = Vector2.new(0.7,0),
					Font = Enum.Font.SourceSansBold,
				},
			},
			{
				["type"] = "Image",
				["Options"] = {
					Image = "http://www.roblox.com/asset/?id=109251559",
					Size = Vector2.new(2.5,0),
				},
			},
			{
				["type"] = "Text",
				["Options"] = {
					Text = "Puedes aprender a subir canciones al karaoke en este vídeo (copia pega)",
					Size = Vector2.new(0.5,0),
					Font = Enum.Font.SourceSansLight,
				},
			},
			{
				["type"] = "Copy",
				["Options"] = {
					Text = "https://www.roblox.com/games/132457887885313/The-Night-of-Panic",
				},
			},

		},
		-- Página 5
		{
			{
				["type"] = "Text",
				["Options"] = {
					Text = "¿Cómo consigo el dinero para comprar todo eso?",
					Size = Vector2.new(0.7,0),
					Font = Enum.Font.SourceSansBold,
				},
			},
			{
				["type"] = "Text",
				["Options"] = {
					Text = "Puedes obtenerlo subiendo de nivel, pidiendo trabajo a los NPCs en los diferentes mundos.",
					Size = Vector2.new(0.5,0),
					Font = Enum.Font.SourceSansLight,
				},
			},

		},

	}
}