local StatsConfig = {
	hunger = {
		message = "¡Tengo mucha hambre!",
		imageId = 125017038675295,
		soundId = 79108210223015
	},
	thirst = {
		message = "¡Estoy muy sediento!",
		imageId = 105422589738943,
		soundId = 91240173636530
	},
	sleepness = {
		message = "¡Qué sueño! Necesito descansar",
		imageId = 122097466233433,
		soundId = 74411148155302		
	},
	hygiene = {
		message = "Creo que ya empiezo a oler...",
		imageId = 96758344081435,
		soundId = 102269049457877
	},
	bladder = {
		message = "¡Necesito ir al baño urgentemente!",
		imageId = 128357516264370,
		soundId = 81989734311069
	},
	physic = {
		message = "Parece que estoy en baja forma",
		imageId = 113121847777046,
		soundId = 103116649516921
	},
}

return StatsConfig
