local HousesInfo = {
	["defaultRoom"] = {
		placeId = 126499097860226,
		name = "Casita a las afueras",
		description = "Casa tranquila",
		price = 0,
		currency = "Coins",
		imageId = "rbxassetid://123456789",
		rarityWeight = 0,
		IsForSale = false,
		MainImage = "rbxassetid://112782519673653",
		Previews = {
			"rbxassetid://112782519673653",
			"rbxassetid://112782519673653",
			"rbxassetid://112782519673653"
		}
	},
	
	["playaRoom"] = {
		placeId = 126499097860226,
		name = "Casa de Playa xd",
		description = "lo mismo que la default",
		price = 4000,
		currency = "Coins",
		imageId = "rbxassetid://123456789",
		rarityWeight = 50,
		IsForSale = true,
		MainImage = "rbxassetid://112782519673653",
		Previews = {
			"rbxassetid://112782519673653",
			"rbxassetid://118816528350790",
			"rbxassetid://135433661017968"
		}
	},
	
	["VistaLujosaRoom"] = {
		placeId = 80492586639096,
		name = "Casa Vista Lujosa",
		description = "lo mismo que la default",
		price = 8000,
		currency = "Coins",
		imageId = "rbxassetid://123456789",
		rarityWeight = 80,
		IsForSale = true,
		MainImage = "rbxassetid://90268856316567",
		Previews = {
			"rbxassetid://90268856316567",
			"rbxassetid://92947227975199",
			"rbxassetid://95403327732674"
		}
	},
}

return HousesInfo
