return {
	SpyJetpack = {
		Name = 'SpyJetpack',
		Value = true,
		DefaultSlot = 1 -- slot por defecto de la wheel/mochila
	},
	Walkie = {
		Name = 'Walkie',
		Value = true,
		DefaultSlot = 2
	},
	Tijeras = {
		Name = 'Tijeras',
		Value = true,
		DefaultSlot = 3
	},
	Cannon = {
		Name = 'Cannon',
		Value = true,
		DefaultSlot = 4
	},
	GloveGun = {
		Name = 'GloveGun',
		Value = true,
		DefaultSlot = 5
	},
	Ballon = {
		Name = 'GloveGun',
		Value = true,
		DefaultSlot = 6
	},
	-- Ejemplo de una herramienta que tienes pero NO va a la rueda:
	SelfieStick = {
		Name = 'SelfieStick',
		Value = true
		-- Al no tener DefaultSlot, se guarda en inventario pero no en la rueda
	},
	SlimeBomb = {
		Name = 'SlimeBomb',
		Value = true
		-- Al no tener DefaultSlot, se guarda en inventario pero no en la rueda
	},
	MiniPotion = {
		Name = 'MiniPotion',
		Value = true
		-- Al no tener DefaultSlot, se guarda en inventario pero no en la rueda
	},
	BigPotion = {
		Name = 'BigPotion',
		Value = true
		-- Al no tener DefaultSlot, se guarda en inventario pero no en la rueda
	}
}