local module = {}

module.Gui = {
	Name = script.Parent.Name,
	Description = [[
	uawhuduoahwudhouhnasuobd baouwb dawnduoabuyowid aw
	awdouabwudalw cadbaiybuob3oabouaousnocubo ap3
	apiwca7oh3nasncoyu ba3
	iñanod n3anousd 
	aapindfo73gahou4noub7dg 97a3
	ouha7gba39hdfa0 89a73h abiay2
	]],
	Icon = nil,
}

module.Data = {
	Name = script.Parent.Name,
	Value = false,
}

module.IsProductPurchase = false
module.Premium = false
module.Price = {Coins = 30, Gems = 10}

module.section = {"All"}
module.Format = "Floors"

return module